# tomcat
server:
  port: 9000
spring:
  application:
    name: vuebg-auto-generator
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.200.112:3306/suphowe?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8
    username: root
    password: root
beetl:
  templatesPath: templates

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8700/eureka/